### ISSUE TITLE
ask for model for 3d printer

### ISSUE THREAD

**Issue by martinbayo** [makertum/Hoverlay-II#1]
Hello Moritz, did you have the model for 3d printer ? , the full model is to big for a normal printer
Thanks

**Comment by makertum** [comment]
Hi, I only have the models provided in this repo. Please use a bigger printer ;)

**Comment by martinbayo** [comment]
Hi moritz, finally i tried to create in freecad a model inspired in you work, here the files https://gitlab.com/martinbayo/pantalla-de-vapor.
Thanks
